name: "Tests"

on: [push]

jobs:
  test:
    timeout-minutes: 10
    strategy:
      matrix:
        nim: [ 'stable' ]
        os: [ 'ubuntu-22.04' ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: install ldap2 valgrind
        run: sudo apt install libldap2-dev valgrind -y
      - uses: actions/checkout@v2
      # - uses: actions/cache@v2
      #   with:
      #     path: ~/.nimble
      #     key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim }}
      - run: nim --version && nimble install -d -y && nimble fulltest -y
